In [ ]:
import pandas as pd

In [ ]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB"
df = pd.read_csv(path)

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_7th Phase JP Nagar  location_Yelahanka  location_Kanakpura Road  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   0                        0   
3                            0                   0                        0   
4                            0                   0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Kasavanhalli  location_Bellandur  location_Begur Road  \
0                      0                   0                    0   
1               

Data Split

In [ ]:
X = df.drop('price', axis=1)
y = df['price']
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)


Random Forest Regression Model Training

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=100,criterion='friedman_mse')
rf.fit(X_train, y_train)

RandomForestRegressor(criterion='friedman_mse')

In [ ]:
rf.score(X_test,y_test)

0.8872694103645441

In [ ]:
rf_100 = RandomForestRegressor(n_estimators=500,criterion='friedman_mse')
rf_100.fit(X_train, y_train)

RandomForestRegressor(criterion='friedman_mse', n_estimators=500)

In [ ]:
rf_100.score(X_test,y_test)

0.8952136517499594

Predict new data

In [ ]:
import numpy as np
arr = np.array([4.5, 3.2, 1890.0, 2, 10234.56789, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
new = pd.DataFrame(arr.reshape([1,-1]), columns=X.columns)

In [ ]:
rf.predict(new )

array([192.12])

Predict The Home Value

In [ ]:
X_test.iloc[-1,:]

bath                               2.000000
balcony                            0.000000
total_sqft_int                  1566.000000
bhk                                2.000000
price_per_sqft                 11494.252874
                                   ...     
location_Hosur Road                0.000000
location_Horamavu Banaswadi        0.000000
location_Domlur                    0.000000
location_Mahadevpura               0.000000
location_Tumkur Road               0.000000
Name: 43, Length: 107, dtype: float64

In [ ]:
new2 = pd.DataFrame(X_test.iloc[-1,:].values.reshape([1,-1]), columns=X.columns)

In [ ]:
rf.predict(new2)

array([175.03])

In [ ]:
y_test.iloc[-1]

180.0

In [ ]:
pred = rf.predict(X_test)
pred

array([ 80.6412,  39.9878, 119.4   , ...,  33.4011,  63.3406, 175.03  ])

In [ ]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64