In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [ ]:
df = pd.read_csv('svm_dataset (1).csv')

In [ ]:
df

Feature1  Feature2  Class
0    -2.509198 -4.765886      0
1     9.014286 -5.060424      1
2     4.639879  8.125092      1
3     1.973170 -5.009076      0
4    -6.879627 -4.561005      0
...        ...       ...    ...
1995  3.139103 -1.157859      1
1996  9.132292 -3.311976      1
1997 -8.620840 -2.108554      0
1998 -8.858906  0.598812      0
1999 -4.356259 -6.772653      0

[2000 rows x 3 columns]

In [ ]:
X = df.drop('Class', axis=1)
y = df['Class']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
model = SVC(kernel='linear', random_state=0)
model.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
model.score(X_train, y_train)

0.99625

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,

In [ ]:
y_test

1860    1
353     1
1333    1
905     0
1289    0
       ..
965     1
1284    0
1739    0
261     1
535     1
Name: Class, Length: 400, dtype: int64

In [ ]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

Actual  Predicted
1860       1          1
353        1          1
1333       1          1
905        0          0
1289       0          0
...      ...        ...
965        1          1
1284       0          0
1739       0          0
261        1          1
535        1          1

[400 rows x 2 columns]

In [ ]:
accrocy = accuracy_score(y_test, y_pred)
confusion_m = confusion_matrix(y_test, y_pred)
classification_reports = classification_report(y_test, y_pred)

In [ ]:
print(accrocy)
print(confusion_m)
print(classification_reports)

0.995
[[198   0]
 [  2 200]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       198
           1       1.00      0.99      1.00       202

    accuracy                           0.99       400
   macro avg       0.99      1.00      0.99       400
weighted avg       1.00      0.99      1.00       400



In [ ]:
from sklearn.model_selection import GridSearchCV

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 0.1, 1, 10]
}

# Initialize SVM and GridSearch
grid_search = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Best hyperparameters
print("Best Parameters:", grid_search.best_params_)

# Train with best parameters
best_svm = grid_search.best_estimator_
best_svm.fit(X_train, y_train)


Best Parameters: {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}


SVC(C=100, kernel='linear')

In [ ]:
y_pred2 = best_svm.predict(X_test)
y_pred2

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,

In [ ]:
y_test

1860    1
353     1
1333    1
905     0
1289    0
       ..
965     1
1284    0
1739    0
261     1
535     1
Name: Class, Length: 400, dtype: int64

In [ ]:
accrocy_best = accuracy_score(y_test, y_pred2)
confusion_m_best = confusion_matrix(y_test, y_pred2)
classification_reports_best = classification_report(y_test, y_pred2)

In [ ]:
print(accrocy_best)
print(confusion_m_best)
print(classification_reports_best)

1.0
[[198   0]
 [  0 202]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       198
           1       1.00      1.00      1.00       202

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400



In [ ]:
predict_df2 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred2})
predict_df2

Actual  Predicted
1860       1          1
353        1          1
1333       1          1
905        0          0
1289       0          0
...      ...        ...
965        1          1
1284       0          0
1739       0          0
261        1          1
535        1          1

[400 rows x 2 columns]