In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('titanic.csv')

In [ ]:
df.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [ ]:
df = df.drop(columns=["Name"])

In [ ]:
df.head()

Survived  Pclass     Sex   Age  Siblings/Spouses Aboard  \
0         0       3    male  22.0                        1   
1         1       1  female  38.0                        1   
2         1       3  female  26.0                        0   
3         1       1  female  35.0                        1   
4         0       3    male  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])

In [ ]:
df.head()

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0         0       3    1  22.0                        1   
1         1       1    0  38.0                        1   
2         1       3    0  26.0                        0   
3         1       1    0  35.0                        1   
4         0       3    1  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [ ]:
X=df.drop(columns=["Fare"])
y=df["Fare"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
model = SVR(kernel='poly')
model.fit(X_train_sc, y_train)

SVR(kernel='poly')

In [ ]:
model.score(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


-138080.10021601006

In [ ]:
#####

df.head()

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0         0       3    1  22.0                        1   
1         1       1    0  38.0                        1   
2         1       3    0  26.0                        0   
3         1       1    0  35.0                        1   
4         0       3    1  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [ ]:
df = pd.read_csv('titanic.csv')

In [ ]:
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])

In [ ]:
df.drop(columns=["Name"], inplace=True)

In [ ]:
df.isnull().sum()

Survived                   0
Pclass                     0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [ ]:
df.head()

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0         0       3    1  22.0                        1   
1         1       1    0  38.0                        1   
2         1       3    0  26.0                        0   
3         1       1    0  35.0                        1   
4         0       3    1  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [ ]:
X = df.drop(columns=["Fare"])
y = df["Fare"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly = PolynomialFeatures(degree=12)
X_train_poly = poly.fit_transform(X_train_sc)
X_test_poly = poly.transform(X_test_sc)

In [ ]:
poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

LinearRegression()

In [ ]:
poly_model.score(X_train_poly, y_train)

0.7753278265038729

In [ ]:
X_test_poly[0,:]

array([ 1.00000000e+00,  1.25625707e+00, -1.57773416e+00, ...,
        1.29398662e-04,  1.30669915e-04,  1.31953658e-04])

In [ ]:
poly_model.predict([X_test_poly[0,:]])

array([39.45042999])

In [ ]:
y_pred = poly_model.predict(X_test_poly)
y_pred

array([ 3.94504300e+01,  5.87493973e+02,  1.11842000e+01, -6.30609856e+01,
        2.60846086e+00, -3.82494369e+01,  2.27624148e+01,  8.73030609e+00,
        1.04537862e+01,  8.07222436e+00,  1.65507163e+02,  1.45628505e+02,
       -4.66775317e+02,  7.45925145e+00,  1.41333415e+01,  1.11279031e+01,
        8.30288952e+00,  5.75093503e+01,  7.13784477e+00,  7.79844932e+00,
        1.40155522e+01,  1.52505671e+01,  9.45604872e+00,  1.34234038e+06,
       -5.89566422e+05,  2.56775762e+01,  1.86961351e+01,  2.18960264e+01,
        1.39032107e+01,  2.03281371e+00,  5.68807357e+01,  7.63785852e+04,
        1.89976236e+01,  1.02104662e+01,  2.29391596e+02, -1.21844630e+02,
        7.94006990e+00,  1.54844825e+02,  1.66483363e+01, -3.09393284e+04,
        1.27996561e+02, -1.29096268e+05,  1.53819509e+01,  7.97242226e+00,
        1.19884525e+01, -1.48280274e+02,  1.39032107e+01,  9.63340171e+00,
        1.38356240e+01,  8.48575046e+00,  5.67264026e+04, -1.65647434e+02,
        7.83609995e+00,  

In [ ]:
y_test

296    30.5000
682    41.5792
535    14.5000
644    35.5000
623    12.3500
        ...   
25     31.3875
84     15.8500
10     16.7000
442    81.8583
762    39.6000
Name: Fare, Length: 178, dtype: float64

In [ ]:
Predict_df = pd.DataFrame({'Predicted': y_pred, 'Actual': y_test})

Predict_df

Predicted   Actual
296  3.945043e+01  30.5000
682  5.874940e+02  41.5792
535  1.118420e+01  14.5000
644 -6.306099e+01  35.5000
623  2.608461e+00  12.3500
..            ...      ...
25  -4.624695e+07  31.3875
84   1.999539e+04  15.8500
10   1.972410e+03  16.7000
442  1.631043e+05  81.8583
762  8.474078e+01  39.6000

[178 rows x 2 columns]